enum CuisineType {
  all,
  african,
  american,
  british,
  cajun,
  caribbean,
  chinese,
  easternEuropean,
  european,
  french,
  german,
  greek,
  indian,
  irish,
  italian,
  japanese,
  jewish,
  korean,
  latinAmerican,
  mediterranean,
  mexican,
  middleEastern,
  nordic,
  southern,
  spanish,
  thai,
  vietnamese,
}



enum RecipeMealType {
  all,
  mainCourse,
  sideDish,
  dessert,
  appetizer,
  salad,
  bread,
  breakfast,
  soup,
  beverage,
  sauce,
  marinade,
  fingerfood,
  snack,
  drink
}

enum DietType {
  all,
  glutenFree,
  ketogenic,
  vegetarian,
  lactoVegetarian,
  ovoVegetarian,
  vegan,
  pescetarian,
  paleo,
  primal,
  whole30
}

enum IntoleranceTypes {
  dairy,
  egg,
  gluten,
  grain,
  peanut,
  seafood,
  sesame,
  shellfish,
  soy,
  sulfite,
  treeNut,
  wheat,
}

enum RecipeSortBy {
  metaScore,
  popularity,
  healthiness,
  price,
  time,
  random,
  maxUsedIngredients,
  minMissingIngredients,
  alcohol,
  caffeine,
  copper,
  energy,
  calories,
  calcium,
  carbohydrates,
  carbs,
  choline,
  cholesterol,
  totalFat,
  fluoride,
  transFat,
  saturatedFat,
  monoUnsaturatedFat,
  polyUnsaturatedFat,
  fiber,
  folate,
  folicAcid,
  iodine,
  iron,
  magnesium,
  manganese,
  vitaminB3,
  niacin,
  vitaminB5,
  pantothenicAcid,
  phosphorus,
  potassium,
  protein,
  vitaminB2,
  riboflavin,
  selenium,
  sodium,
  vitaminB1,
  thiamin,
  vitaminA,
  vitaminB6,
  vitaminB12,
  vitaminC,
  vitaminD,
  vitaminE,
  vitaminK,
  sugar,
  zinc,
}

const Map<RecipeSortBy, String> recipeSortByToString = {
  RecipeSortBy.metaScore: 'meta-score',
  RecipeSortBy.popularity: 'popularity',
  RecipeSortBy.healthiness: 'healthiness',
  RecipeSortBy.price: 'price',
  RecipeSortBy.time: 'time',
  RecipeSortBy.random: 'random',
  RecipeSortBy.maxUsedIngredients: 'max-used-ingredients',
  RecipeSortBy.minMissingIngredients: 'min-missing-ingredients',
  RecipeSortBy.alcohol: 'alcohol',
  RecipeSortBy.caffeine: 'caffeine',
  RecipeSortBy.copper: 'copper',
  RecipeSortBy.energy: 'energy',
  RecipeSortBy.calories: 'calories',
  RecipeSortBy.calcium: 'calcium',
  RecipeSortBy.carbohydrates: 'carbohydrates',
  RecipeSortBy.carbs: 'carbs',
  RecipeSortBy.choline: 'choline',
  RecipeSortBy.cholesterol: 'cholesterol',
  RecipeSortBy.totalFat: 'total-fat',
  RecipeSortBy.fluoride: 'fluoride',
  RecipeSortBy.transFat: 'trans-fat',
  RecipeSortBy.saturatedFat: 'saturated-fat',
  RecipeSortBy.monoUnsaturatedFat: 'mono-unsaturated-fat',
  RecipeSortBy.polyUnsaturatedFat: 'poly-unsaturated-fat',
  RecipeSortBy.fiber: 'fiber',
  RecipeSortBy.folate: 'folate',
  RecipeSortBy.folicAcid: 'folic-acid',
  RecipeSortBy.iodine: 'iodine',
  RecipeSortBy.iron: 'iron',
  RecipeSortBy.magnesium: 'magnesium',
  RecipeSortBy.manganese: 'manganese',
  RecipeSortBy.vitaminB3: 'vitamin-b3',
  RecipeSortBy.niacin: 'niacin',
  RecipeSortBy.vitaminB5: 'vitamin-b5',
  RecipeSortBy.pantothenicAcid: 'pantothenic-acid',
  RecipeSortBy.phosphorus: 'phosphorus',
  RecipeSortBy.potassium: 'potassium',
  RecipeSortBy.protein: 'protein',
  RecipeSortBy.vitaminB2: 'vitamin-b2',
  RecipeSortBy.riboflavin: 'riboflavin',
  RecipeSortBy.selenium: 'selenium',
  RecipeSortBy.sodium: 'sodium',
  RecipeSortBy.vitaminB1: 'vitamin-b1',
  RecipeSortBy.thiamin: 'thiamin',
  RecipeSortBy.vitaminA: 'vitamin-a',
  RecipeSortBy.vitaminB6: 'vitamin-b6',
  RecipeSortBy.vitaminB12: 'vitamin-b12',
  RecipeSortBy.vitaminC: 'vitamin-c',
  RecipeSortBy.vitaminD: 'vitamin-d',
  RecipeSortBy.vitaminE: 'vitamin-e',
  RecipeSortBy.vitaminK: 'vitamin-k',
  RecipeSortBy.sugar: 'sugar',
  RecipeSortBy.zinc: 'zinc',
};

const Map<IntoleranceTypes, String> intoleranceTypesToString = {
  IntoleranceTypes.dairy: 'Dairy',
  IntoleranceTypes.egg: 'Egg',
  IntoleranceTypes.gluten: 'Gluten',
  IntoleranceTypes.grain: 'Grain',
  IntoleranceTypes.peanut: 'Peanut',
  IntoleranceTypes.seafood: 'Seafood',
  IntoleranceTypes.sesame: 'Sesame',
  IntoleranceTypes.shellfish: 'Shellfish',
  IntoleranceTypes.soy: 'Soy',
  IntoleranceTypes.sulfite: 'Sulfite',
  IntoleranceTypes.treeNut: 'Tree Nut',
  IntoleranceTypes.wheat: 'Wheat'
};

const Map<DietType, String> dietTypeToString = {
  DietType.all: "All",
  DietType.glutenFree: "GlutenFree",
  DietType.ketogenic: "Ketogenic",
  DietType.vegetarian: "Vegetarian",
  DietType.lactoVegetarian: "Lacto-Vegetarian",
  DietType.ovoVegetarian: "Ovo-Vegetarian",
  DietType.vegan: "Vegan",
  DietType.pescetarian: "Pescetarian",
  DietType.paleo: "Paleo",
  DietType.primal: "Primal",
  DietType.whole30: "Whole30",
};

const Map<RecipeMealType, String> recipeMealTypeToString = {
  RecipeMealType.all: 'All',
  RecipeMealType.mainCourse: 'main course',
  RecipeMealType.sideDish: 'side dish',
  RecipeMealType.dessert: 'dessert',
  RecipeMealType.appetizer: 'appetizer',
  RecipeMealType.salad: 'salad',
  RecipeMealType.bread: 'bread',
  RecipeMealType.breakfast: 'breakfast',
  RecipeMealType.soup: 'soup',
  RecipeMealType.beverage: 'beverage',
  RecipeMealType.sauce: 'sauce',
  RecipeMealType.marinade: 'marinade',
  RecipeMealType.fingerfood: 'fingerfood',
  RecipeMealType.snack: 'snack',
  RecipeMealType.drink: 'drink',
};

const Map<CuisineType, String> cuisineTypeToString = {
  CuisineType.all: 'All',
  CuisineType.african: 'African',
  CuisineType.american: 'American',
  CuisineType.british: 'British',
  CuisineType.cajun: 'Cajun',
  CuisineType.caribbean: 'Caribbean',
  CuisineType.chinese: 'Chinese',
  CuisineType.easternEuropean: 'Eastern European',
  CuisineType.european: 'European',
  CuisineType.french: 'French',
  CuisineType.german: 'German',
  CuisineType.greek: 'Greek',
  CuisineType.indian: 'Indian',
  CuisineType.irish: 'Irish',
  CuisineType.italian: 'Italian',
  CuisineType.japanese: 'Japanese',
  CuisineType.jewish: 'Jewish',
  CuisineType.korean: 'Korean',
  CuisineType.latinAmerican: 'Latin American',
  CuisineType.mediterranean: 'Mediterranean',
  CuisineType.mexican: 'Mexican',
  CuisineType.middleEastern: 'Middle Eastern',
  CuisineType.nordic: 'Nordic',
  CuisineType.southern: 'Southern',
  CuisineType.spanish: 'Spanish',
  CuisineType.thai: 'Thai',
  CuisineType.vietnamese: 'Vietnamese'
};