// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCax3iCS54N9xTxyy4zV3y9K1bX_FXMMNo',
    appId: '1:725086250534:web:da07d22a2c6b71d66828e7',
    messagingSenderId: '725086250534',
    projectId: 'z-fitness',
    authDomain: 'z-fitness.firebaseapp.com',
    storageBucket: 'z-fitness.appspot.com',
    measurementId: 'G-FSBQK8DKGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6aq1rQXeHvCbL7yXwgnw_jEbOm0NimSw',
    appId: '1:725086250534:android:9512881a21e5a8386828e7',
    messagingSenderId: '725086250534',
    projectId: 'z-fitness',
    storageBucket: 'z-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyWICq6dwc4NHctusiWH63jYHD2h8HVg',
    appId: '1:725086250534:ios:4f936a7a85afac636828e7',
    messagingSenderId: '725086250534',
    projectId: 'z-fitness',
    storageBucket: 'z-fitness.appspot.com',
    iosClientId: '725086250534-p9u6bl67tb360kak9ramrqqv35nju6fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.zFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyWICq6dwc4NHctusiWH63jYHD2h8HVg',
    appId: '1:725086250534:ios:0f1579b01011e3e06828e7',
    messagingSenderId: '725086250534',
    projectId: 'z-fitness',
    storageBucket: 'z-fitness.appspot.com',
    iosClientId: '725086250534-5lqqk21o7m23sim3eu9l4b9dbrj7kr4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.zF',
  );
}
