// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCax3iCS54N9xTxyy4zV3y9K1bX_FXMMNo',
    appId: '1:725086250534:web:cf3bc2d4466b55396828e7',
    messagingSenderId: '725086250534',
    projectId: 'z-fitness',
    authDomain: 'z-fitness.firebaseapp.com',
    storageBucket: 'z-fitness.appspot.com',
    measurementId: 'G-N7Y3S4FP2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6aq1rQXeHvCbL7yXwgnw_jEbOm0NimSw',
    appId: '1:725086250534:android:3920e8318c6e81676828e7',
    messagingSenderId: '725086250534',
    projectId: 'z-fitness',
    storageBucket: 'z-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyWICq6dwc4NHctusiWH63jYHD2h8HVg',
    appId: '1:725086250534:ios:1e7d0a4e9bbe20486828e7',
    messagingSenderId: '725086250534',
    projectId: 'z-fitness',
    storageBucket: 'z-fitness.appspot.com',
    iosClientId: '725086250534-ld3fjlv92805ambivo6sqa6vlmd0qf8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.zFitness',
  );
}
